export * from './advertisement.service';
import { AdvertisementService } from './advertisement.service';
export * from './auth.service';
import { AuthService } from './auth.service';
export * from './candidate.service';
import { CandidateService } from './candidate.service';
export * from './competence.service';
import { CompetenceService } from './competence.service';
export * from './condition.service';
import { ConditionService } from './condition.service';
export * from './document.service';
import { DocumentService } from './document.service';
export * from './domainActivity.service';
import { DomainActivityService } from './domainActivity.service';
export * from './education.service';
import { EducationService } from './education.service';
export * from './favorite.service';
import { FavoriteService } from './favorite.service';
export * from './formation.service';
import { FormationService } from './formation.service';
export * from './group.service';
import { GroupService } from './group.service';
export * from './invoice.service';
import { InvoiceService } from './invoice.service';
export * from './log.service';
import { LogService } from './log.service';
export * from './message.service';
import { MessageService } from './message.service';
export * from './newsletter.service';
import { NewsletterService } from './newsletter.service';
export * from './oauthProvider.service';
import { OauthProviderService } from './oauthProvider.service';
export * from './package.service';
import { PackageService } from './package.service';
export * from './payment.service';
import { PaymentService } from './payment.service';
export * from './permission.service';
import { PermissionService } from './permission.service';
export * from './profession.service';
import { ProfessionService } from './profession.service';
export * from './project.service';
import { ProjectService } from './project.service';
export * from './question.service';
import { QuestionService } from './question.service';
export * from './review.service';
import { ReviewService } from './review.service';
export * from './role.service';
import { RoleService } from './role.service';
export * from './specialism.service';
import { SpecialismService } from './specialism.service';
export * from './status.service';
import { StatusService } from './status.service';
export * from './subscription.service';
import { SubscriptionService } from './subscription.service';
export * from './task.service';
import { TaskService } from './task.service';
export * from './testimonial.service';
import { TestimonialService } from './testimonial.service';
export * from './typeDocument.service';
import { TypeDocumentService } from './typeDocument.service';
export * from './user.service';
import { UserService } from './user.service';
export const APIS = [AdvertisementService, AuthService, CandidateService, CompetenceService, ConditionService, DocumentService, DomainActivityService, EducationService, FavoriteService, FormationService, GroupService, InvoiceService, LogService, MessageService, NewsletterService, OauthProviderService, PackageService, PaymentService, PermissionService, ProfessionService, ProjectService, QuestionService, ReviewService, RoleService, SpecialismService, StatusService, SubscriptionService, TaskService, TestimonialService, TypeDocumentService, UserService];
