/**
 * API Candidats
 * API pour la gestion des candidats
 *
 * OpenAPI spec version: v1
 * Contact: contact@votreapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Body3 { 
    /**
     * Nouveau statut du projet
     */
    statut?: Body3.StatutEnum;
}
export namespace Body3 {
    export type StatutEnum = 'en_attente' | 'en_cours' | 'termine' | 'annule';
    export const StatutEnum = {
        EnAttente: 'en_attente' as StatutEnum,
        EnCours: 'en_cours' as StatutEnum,
        Termine: 'termine' as StatutEnum,
        Annule: 'annule' as StatutEnum
    };
}