/**
 * API Candidats
 * API pour la gestion des candidats
 *
 * OpenAPI spec version: v1
 * Contact: contact@votreapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface CustomUser { 
    email: string;
    userType?: CustomUser.UserTypeEnum;
}
export namespace CustomUser {
    export type UserTypeEnum = 'candidat' | 'entreprise' | 'user';
    export const UserTypeEnum = {
        Candidat: 'candidat' as UserTypeEnum,
        Entreprise: 'entreprise' as UserTypeEnum,
        User: 'user' as UserTypeEnum
    };
}