/**
 * API Candidats
 * API pour la gestion des candidats
 *
 * OpenAPI spec version: v1
 * Contact: contact@votreapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Tache { 
    readonly id?: number;
    readonly candidat?: number;
    title: string;
    description?: string;
    dueDate?: string;
    completed?: boolean;
    readonly createdAt?: Date;
    readonly updatedAt?: Date;
}