/**
 * API Candidats
 * API pour la gestion des candidats
 *
 * OpenAPI spec version: v1
 * Contact: contact@votreapi.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Utilisateur { 
    readonly id?: number;
    nom: string;
    prenom: string;
    role?: Utilisateur.RoleEnum;
    email: string;
    userType: string;
    password: string;
    sexe?: Utilisateur.SexeEnum;
    dateNaissance?: string;
    lieuNaissance?: string;
    telephone?: string;
    address?: string;
}
export namespace Utilisateur {
    export type RoleEnum = 'admin' | 'manager' | 'comptable' | 'user';
    export const RoleEnum = {
        Admin: 'admin' as RoleEnum,
        Manager: 'manager' as RoleEnum,
        Comptable: 'comptable' as RoleEnum,
        User: 'user' as RoleEnum
    };
    export type SexeEnum = 'M' | 'F';
    export const SexeEnum = {
        M: 'M' as SexeEnum,
        F: 'F' as SexeEnum
    };
}