export * from './auth.service';
import { AuthService } from './auth.service';
export * from './candidats.service';
import { CandidatsService } from './candidats.service';
export * from './educations.service';
import { EducationsService } from './educations.service';
export * from './entreprises.service';
import { EntreprisesService } from './entreprises.service';
export * from './experiences.service';
import { ExperiencesService } from './experiences.service';
export * from './projets.service';
import { ProjetsService } from './projets.service';
export * from './taches.service';
import { TachesService } from './taches.service';
export * from './users.service';
import { UsersService } from './users.service';
export const APIS = [AuthService, CandidatsService, EducationsService, EntreprisesService, ExperiencesService, ProjetsService, TachesService, UsersService];
