/**
 * Api documentation
 * Api documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: codeguessdev237@codeguess.cm
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Advertisement { 
    title?: string;
    description?: string;
    periodStart?: Date;
    periodEnd?: Date;
    /**
     * Public cible de la publicité (par exemple, âge, sexe, intérêt).
     */
    cible: string;
    /**
     * Type de formation (présentiel, en ligne, hybride, etc.)
     */
    imageUrl?: string;
    /**
     * Niveau de la formation (débutant, intermédiaire, avancé, etc.)
     */
    videoUrl?: string;
    /**
     * Statut de la publicité (par exemple, active, inactive, expirée).
     */
    status?: string;
    /**
     * Budget alloué pour la publicité.
     */
    budget?: number;
    readonly createdAt?: Date;
    readonly updatedAt?: Date;
    readonly deletedAt?: Date;
}