/**
 * Api documentation
 * Api documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: codeguessdev237@codeguess.cm
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Message { 
    name?: string;
    email?: string;
    phone?: string;
    subject?: string;
    message?: string;
    picture?: string;
    readonly deletedAt?: Date;
    readonly createdAt?: Date;
    readonly updatedAt?: Date;
}