/**
 * Api documentation
 * Api documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: codeguessdev237@codeguess.cm
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Project { 
    readonly id?: string;
    name?: string;
    description?: string;
    enable?: boolean;
    status: string;
    dateEnd?: string;
    dateStart?: string;
    dateExpired?: string;
    clientPrice?: number;
    /**
     * Fixed , Variable 
     */
    priceType: string;
    validateProject: string;
    freelancerPrice?: number;
    readonly createdAt?: Date;
    readonly updatedAt?: Date;
    readonly deletedAt?: Date;
}