/**
 * Api documentation
 * Api documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: codeguessdev237@codeguess.cm
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface Status { 
    /**
     * &#039;pending&#039;, &#039;inprogress&#039;, &#039;completed&#039;, &#039;cancelled&#039;, &#039;failed&#039;,&#039;faid&#039;
     */
    readonly id?: string;
    /**
     * &#039;Pending&#039;, &#039;In Progress&#039;, &#039;Completed&#039;, &#039;Cancelled&#039;, &#039;Failed&#039;,&#039;Paid&#039;
     */
    name?: string;
}