/**
 * Api documentation
 * Api documentation
 *
 * OpenAPI spec version: 1.0.0
 * Contact: codeguessdev237@codeguess.cm
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

export interface TypeDocument { 
    /**
     * &#039;cv&#039;, &#039;cni&#039;, &#039;passport&#039;, &#039;other&#039;
     */
    name?: string;
    enable?: boolean;
    readonly createdAt?: Date;
}